source 'http://rubygems.org'

ruby '2.0.0'

gem 'rails', '~> 4.0.3'
gem 'mysql2', '~> 0.3.0'
gem 'sanitize', '~> 3.0.0'
gem 'csspool', '~> 4.0.2'
gem 'public_suffix', '~> 1.3.1'
gem 'thinking-sphinx', '~> 3.1.1'
gem 'riddle', '~> 1.5.11'
gem 'ts-delayed-delta', '~> 2.0.0'
gem 'delayed_job', '~> 4.0.0'
gem 'delayed_job_active_record', '~> 4.0.0'
gem 'will_paginate', '~> 3.0.5'
gem 'ruby-openid', '~> 2.3.0'
gem 'strip_attributes', '~> 1.5.0'
gem 'dynamic_form', '~> 1.1.4'
gem 'dalli', '~> 2.6.4'
gem 'rails-observers', '~> 0.1.2'
gem 'ignorable', '~> 0.2.0'
gem 'daemons'
gem 'newrelic_rpm'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'therubyracer'
gem 'yui-compressor'
